version: "3.9"
services:
  backend:
    build: .
    environment:
      - DEBUG=1
    ports:
      - "8082:8082"
    volumes:
      - "~/persist:/var/persist"

  frontend:
    build: ./web
    ports:
      - "8081:8081"