version: "3.9"
services:
  backend:
    build: .
    ports:
      - "8082:8082"

  frontend:
    build: ./web
    ports:
      - "8081:8081"

  nginx:
    build: "./nginx"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./m1553d.com:/var/www/m1553d.com
      - /etc/letsencrypt/:/etc/letsencrypt/
    depends_on:
      - "backend"
      - "frontend"